test_size: 0.3
param_space:
  cycle_model:
    regressor__model__n_estimators:
      - 100
      - 250
    regressor__model__learning_rate:
      - 0.1
      - 0.3
    regressor__model__reg_alpha:
      - 0.1
      - 0.001
    regressor__model__max_depth:
      - 2
  capacity_ir_model:
    regressor__model__n_estimators:
      - 400
      - 500
    regressor__model__learning_rate:
      - 0.1
      - 0.2
    regressor__model__max_depth:
      - 5
      - 6


